### ISSUE TITLE
Middle mouse button click on link to external website opens it in the media player itself

### ISSUE THREAD

**Issue by maggikpunkt** [jellyfin/jellyfin-media-player#173]
If you visit a movie detail page of a movie that has an external id in it's metadata jellyfin displays a link to that external website. Middle mouse clicking on that link opens the website in the browser but also in the jellyfin media player itself. There is no way to get back and the client needs to be restartet.

I'm using JellyfinMediaPlayer-1.6.1-windows-x64.exe on Windows 10

**Comment by XandaPanda42** [comment]
This might have been fixed as it's no longer happening as of 1.11.1 (at least on Windows 11 and Ubuntu).

Can someone with the latest version for Windows 10 confirm?

**Comment by maggikpunkt** [comment]
https://github.com/user-attachments/assets/16bbcc4a-70b9-41ac-952a-198dd294ba7b
Still happening on version 1.11.1 on Microsoft Windows 10 Pro N 10.0.19045 Build 19045

**Comment by andrewrabert** [comment]
This Qt desktop client has been deprecated in favor of a rewrite: https://github.com/jellyfin/jellyfin-desktop
