### ISSUE TITLE
Cannot connect to any server if cannot connect to previously logged in server

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-media-player#747]
**Describe the bug**
Cannot connect to any server under certain circumstances

**To Reproduce**
1. Connect to a Jellyfin server in JMP, login then close JMP
2. Shut down the server JMP was previously connected to and keep it off. The bug will not happen if you outright disconnect the client from the internet. (I shutdown the entire host computer of the server in my testing)
3. Open JMP and attempt to connect to any server
4. See error (cannot click connect)

**Expected behavior**
Connect button should be light blue and clickable, instead of greyed out and not clickable

**Screenshots**
![Screenshot from 2024-08-19 00-59-14](https://github.com/user-attachments/assets/9cadd732-d2ff-47fa-9129-9394b2607932)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 21.3
 - Installation Method: .deb (Ubuntu Jammy)

**Additional context**
Logs:
[jellyfinmediaplayer.log](https://github.com/user-attachments/files/16650449/jellyfinmediaplayer.log)

**Comment by TomIsFat** [comment]
Temporary fix in Windows: Delete these two folders  
`%localappdata%\Jellyfin Media Player`  
`%localappdata%\JellyfinMediaPlayer`

**Comment by thisisshub** [comment]
Does anyone knows how to fix this in macos?

**Comment by raffaeldp** [comment]
Up, for macos anyone has an idea ? 
I have tried to remove the app, then rm -rf the cache for jellyfin media player in /Users/[user]/Library/Caches, then reinstall the app but the issue is still there :(

**Comment by iwalton3** [comment]
Fixed in the latest pre-release.

https://github.com/jellyfin/jellyfin-media-player/releases/tag/v1.12.0-pre1

**Comment by andrewrabert** [comment]
This Qt desktop client has been deprecated in favor of a rewrite: https://github.com/jellyfin/jellyfin-desktop

**Comment by baptistegh** [comment]
@andrewrabert This bug is still here on the new jellyfin-desktop v1.12.0 - I think this issue should be reopened.

I installed my MacOs Client from the release page of https://github.com/jellyfin/jellyfin-desktop
