### ISSUE TITLE
Chunkload Error

### ISSUE THREAD

**Issue by TestingYG** [jellyfin/jellyfin-media-player#798]
**Describe the bug**
Clicking Search icon results in chunkloaderror

**Screenshots**
![Image](https://github.com/user-attachments/assets/6ec505e1-11dc-40b0-b785-287973926e2c)

**Desktop (please complete the following information):**
 - OS: Windows 10 latest update
 - Jellyfin Media Player version - V1.11.1
 - Jellyfin Server Version: 10.10.1
 - Installation Method: windows installer

**Additional context**
Reverting Jellyfin Version from 10.10.1 to 10.10 Fixes the issues.

**Comment by frognet** [comment]
The same problem happens with debian 11 headless-server and Jellyfin Media Player, even with Version 10.10.0 (happens with 10.10.1 and 10.10.2 too)

-  OS: Debian 11
-  jellyfin-web/now 10.10.0+deb11 all
-  jellyfin-server/now 10.10.0+deb11 amd64
-  Installation Method official Jellyfin deb-package

Verified running:
![Image](https://github.com/user-attachments/assets/6c35cd7b-3eac-4be3-9de8-4e739acba38b)

>Unexpected Application Error!
Loading chunk 47588 failed. (error: https://jellyfin.x/web/node_modules.usehooks-ts.d0c0762c8a632c930adf.chunk.js)
ChunkLoadError: Loading chunk 47588 failed.
(error: https://jellyfin.x/web/node_modules.usehooks-ts.d0c0762c8a632c930adf.chunk.js)
    at Object.s.f.j (https://jellyfin.x/web/runtime.bundle.js?4eb8ea179f4fc2baed3a:1:45135)
    at https://jellyfin.x/web/runtime.bundle.js?4eb8ea179f4fc2baed3a:1:1410
    at Array.reduce (<anonymous>)
    at s.e (https://jellyfin.x/web/runtime.bundle.js?4eb8ea179f4fc2baed3a:1:1375)
    at Array.map (<anonymous>)
    at i (https://jellyfin.x/web/main.jellyfin.bundle.js?4eb8ea179f4fc2baed3a:2:470678)
    at Object.requireAsync (https://jellyfin.x/web/main.jellyfin.bundle.js?4eb8ea179f4fc2baed3a:2:431356)
    at _ (https://jellyfin.x/web/60232.bundle.js?4eb8ea179f4fc2baed3a:2:61100)
    at r.n.resolveAsync (https://jellyfin.x/web/60232.bundle.js?4eb8ea179f4fc2baed3a:2:63433)
    at r.n.loadAsync (https://jellyfin.x/web/60232.bundle.js?4eb8ea179f4fc2baed3a:2:63086)

**Comment by frognet** [comment]
Seems the problem is solved with 10.10.3.

**Comment by TestingYG** [comment]
10.10.3 Issues still persists. 

![Image](https://github.com/user-attachments/assets/30ea00ef-b16c-442c-a316-443099577983)

**Comment by TestingYG** [comment]
Duplicate 

https://github.com/jellyfin/jellyfin-media-player/issues/726
